/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedWarehousesIndexRouteImport } from './routes/_authed/warehouses/index'
import { Route as AuthedSuppliersIndexRouteImport } from './routes/_authed/suppliers/index'
import { Route as AuthedStockIndexRouteImport } from './routes/_authed/stock/index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedCustomersIndexRouteImport } from './routes/_authed/customers/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedWarehousesNewRouteImport } from './routes/_authed/warehouses/new'
import { Route as AuthedWarehousesIdRouteImport } from './routes/_authed/warehouses/$id'
import { Route as AuthedSuppliersNewRouteImport } from './routes/_authed/suppliers/new'
import { Route as AuthedSuppliersIdRouteImport } from './routes/_authed/suppliers/$id'
import { Route as AuthedProductsNewRouteImport } from './routes/_authed/products/new'
import { Route as AuthedProductsIdRouteImport } from './routes/_authed/products/$id'
import { Route as AuthedCustomersNewRouteImport } from './routes/_authed/customers/new'
import { Route as AuthedCustomersIdRouteImport } from './routes/_authed/customers/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedWarehousesIndexRoute = AuthedWarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSuppliersIndexRoute = AuthedSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedStockIndexRoute = AuthedStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCustomersIndexRoute = AuthedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWarehousesNewRoute = AuthedWarehousesNewRouteImport.update({
  id: '/warehouses/new',
  path: '/warehouses/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedWarehousesIdRoute = AuthedWarehousesIdRouteImport.update({
  id: '/warehouses/$id',
  path: '/warehouses/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSuppliersNewRoute = AuthedSuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSuppliersIdRoute = AuthedSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsNewRoute = AuthedProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsIdRoute = AuthedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCustomersNewRoute = AuthedCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCustomersIdRoute = AuthedCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/products/$id': typeof AuthedProductsIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/suppliers/$id': typeof AuthedSuppliersIdRoute
  '/suppliers/new': typeof AuthedSuppliersNewRoute
  '/warehouses/$id': typeof AuthedWarehousesIdRoute
  '/warehouses/new': typeof AuthedWarehousesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customers/': typeof AuthedCustomersIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/stock/': typeof AuthedStockIndexRoute
  '/suppliers/': typeof AuthedSuppliersIndexRoute
  '/warehouses/': typeof AuthedWarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/products/$id': typeof AuthedProductsIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/suppliers/$id': typeof AuthedSuppliersIdRoute
  '/suppliers/new': typeof AuthedSuppliersNewRoute
  '/warehouses/$id': typeof AuthedWarehousesIdRoute
  '/warehouses/new': typeof AuthedWarehousesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customers': typeof AuthedCustomersIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/stock': typeof AuthedStockIndexRoute
  '/suppliers': typeof AuthedSuppliersIndexRoute
  '/warehouses': typeof AuthedWarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/customers/$id': typeof AuthedCustomersIdRoute
  '/_authed/customers/new': typeof AuthedCustomersNewRoute
  '/_authed/products/$id': typeof AuthedProductsIdRoute
  '/_authed/products/new': typeof AuthedProductsNewRoute
  '/_authed/suppliers/$id': typeof AuthedSuppliersIdRoute
  '/_authed/suppliers/new': typeof AuthedSuppliersNewRoute
  '/_authed/warehouses/$id': typeof AuthedWarehousesIdRoute
  '/_authed/warehouses/new': typeof AuthedWarehousesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/customers/': typeof AuthedCustomersIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/stock/': typeof AuthedStockIndexRoute
  '/_authed/suppliers/': typeof AuthedSuppliersIndexRoute
  '/_authed/warehouses/': typeof AuthedWarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/customers/$id'
    | '/customers/new'
    | '/products/$id'
    | '/products/new'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/warehouses/$id'
    | '/warehouses/new'
    | '/api/auth/$'
    | '/customers/'
    | '/products/'
    | '/stock/'
    | '/suppliers/'
    | '/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/customers/$id'
    | '/customers/new'
    | '/products/$id'
    | '/products/new'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/warehouses/$id'
    | '/warehouses/new'
    | '/api/auth/$'
    | '/customers'
    | '/products'
    | '/stock'
    | '/suppliers'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/login'
    | '/register'
    | '/_authed/dashboard'
    | '/_authed/customers/$id'
    | '/_authed/customers/new'
    | '/_authed/products/$id'
    | '/_authed/products/new'
    | '/_authed/suppliers/$id'
    | '/_authed/suppliers/new'
    | '/_authed/warehouses/$id'
    | '/_authed/warehouses/new'
    | '/api/auth/$'
    | '/_authed/customers/'
    | '/_authed/products/'
    | '/_authed/stock/'
    | '/_authed/suppliers/'
    | '/_authed/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/warehouses/': {
      id: '/_authed/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof AuthedWarehousesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/suppliers/': {
      id: '/_authed/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthedSuppliersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/stock/': {
      id: '/_authed/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AuthedStockIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers/': {
      id: '/_authed/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthedCustomersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/warehouses/new': {
      id: '/_authed/warehouses/new'
      path: '/warehouses/new'
      fullPath: '/warehouses/new'
      preLoaderRoute: typeof AuthedWarehousesNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/warehouses/$id': {
      id: '/_authed/warehouses/$id'
      path: '/warehouses/$id'
      fullPath: '/warehouses/$id'
      preLoaderRoute: typeof AuthedWarehousesIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/suppliers/new': {
      id: '/_authed/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof AuthedSuppliersNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/suppliers/$id': {
      id: '/_authed/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AuthedSuppliersIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/new': {
      id: '/_authed/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthedProductsNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/$id': {
      id: '/_authed/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthedProductsIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers/new': {
      id: '/_authed/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthedCustomersNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers/$id': {
      id: '/_authed/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthedCustomersIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedCustomersIdRoute: typeof AuthedCustomersIdRoute
  AuthedCustomersNewRoute: typeof AuthedCustomersNewRoute
  AuthedProductsIdRoute: typeof AuthedProductsIdRoute
  AuthedProductsNewRoute: typeof AuthedProductsNewRoute
  AuthedSuppliersIdRoute: typeof AuthedSuppliersIdRoute
  AuthedSuppliersNewRoute: typeof AuthedSuppliersNewRoute
  AuthedWarehousesIdRoute: typeof AuthedWarehousesIdRoute
  AuthedWarehousesNewRoute: typeof AuthedWarehousesNewRoute
  AuthedCustomersIndexRoute: typeof AuthedCustomersIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedStockIndexRoute: typeof AuthedStockIndexRoute
  AuthedSuppliersIndexRoute: typeof AuthedSuppliersIndexRoute
  AuthedWarehousesIndexRoute: typeof AuthedWarehousesIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedCustomersIdRoute: AuthedCustomersIdRoute,
  AuthedCustomersNewRoute: AuthedCustomersNewRoute,
  AuthedProductsIdRoute: AuthedProductsIdRoute,
  AuthedProductsNewRoute: AuthedProductsNewRoute,
  AuthedSuppliersIdRoute: AuthedSuppliersIdRoute,
  AuthedSuppliersNewRoute: AuthedSuppliersNewRoute,
  AuthedWarehousesIdRoute: AuthedWarehousesIdRoute,
  AuthedWarehousesNewRoute: AuthedWarehousesNewRoute,
  AuthedCustomersIndexRoute: AuthedCustomersIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedStockIndexRoute: AuthedStockIndexRoute,
  AuthedSuppliersIndexRoute: AuthedSuppliersIndexRoute,
  AuthedWarehousesIndexRoute: AuthedWarehousesIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
